[project]
name = 'Tokenized-Litigation-Financing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.case-verification]
path = 'contracts/case-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.investment-management]
path = 'contracts/investment-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
